application: divsieapp
version: 1
runtime: python27
api_version: 1
threadsafe: false

inbound_services:
- warmup

handlers:
- url: /_remote_api
  script: remote_api_wsgi.app
  login: admin
  secure: always

- url: /.*
  script: divsieapp.application
  secure: always

builtins:
- appstats: off

libraries:
- name: jinja2
  version: latest
- name: webob
  version: latest
