application: divsieapp
version: 1
runtime: python27
api_version: 1
threadsafe: false

inbound_services:
- warmup

handlers:
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt
  secure: always

- url: /humans\.txt
  static_files: static/humans.txt
  upload: static/humans\.txt
  secure: always

- url: /crossdomain\.xml
  static_files: static/crossdomain.xml
  upload: static/humans\.txt
  secure: always

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  secure: always

- url: /apple-touch-icon(.*)\.png
  static_files: static/apple-touch-icon\1.png
  upload: static/apple-touch-icon(.*)\.png
  secure: always

- url: /_remote_api
  script: remote_api_wsgi.app
  login: admin
  secure: always

- url: /.*
  script: divsieapp.application
  secure: always

builtins:
- appstats: off

libraries:
- name: jinja2
  version: latest
- name: webob
  version: latest
